window.baseDb = {
  classes: [
    {
      name: 'SceneObject',
      displayName: 'SceneObject',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneObject',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'RuntimeInstancedFoliageActor',
      displayName: 'RuntimeInstancedFoliageActor',
      description: '',
      path: 'Class /Script/PiCIMOS.RuntimeInstancedFoliageActor',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCable',
      displayName: 'SceneCable',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCable',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCamera',
      displayName: 'SceneCamera',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCamera',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCameraRail',
      displayName: 'SceneCameraRail',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCameraRail',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCameraArcRail',
      displayName: 'SceneCameraArcRail',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCameraArcRail',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCameraKeyframe',
      displayName: 'SceneCameraKeyframe',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCameraKeyframe',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCameraOrbit',
      displayName: 'SceneCameraOrbit',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCameraOrbit',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCameraPivot',
      displayName: 'SceneCameraPivot',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCameraPivot',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCameraSpline',
      displayName: 'SceneCameraSpline',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCameraSpline',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCameraStraightRail',
      displayName: 'SceneCameraStraightRail',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCameraStraightRail',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCharacter',
      displayName: 'SceneCharacter',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCharacter',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCompass',
      displayName: 'SceneCompass',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCompass',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneCrossRoad',
      displayName: 'SceneCrossRoad',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneCrossRoad',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneDataObject',
      displayName: 'SceneDataObject',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneDataObject',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneDatasmith',
      displayName: 'SceneDatasmith',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneDatasmith',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneDynamicMeshBaseObject',
      displayName: 'SceneDynamicMeshBaseObject',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneDynamicMeshBaseObject',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneDynamicMeshObject',
      displayName: 'SceneDynamicMeshObject',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneDynamicMeshObject',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneEnvData',
      displayName: 'SceneEnvData',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneEnvData',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneFaceLight',
      displayName: 'SceneFaceLight',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneFaceLight',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneInfo',
      displayName: 'SceneInfo',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneInfo',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneIOT',
      displayName: 'SceneIOT',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneIOT',
      classes: ['SceneObject', 'SceneIOT'],
      params: [],
    },
    {
      name: 'SceneLidar',
      displayName: 'SceneLidar',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneLidar',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'ScenePath',
      displayName: 'ScenePath',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePath',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'SceneMeasureTool',
      displayName: 'SceneMeasureTool',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneMeasureTool',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'SceneMeshObject',
      displayName: 'SceneMeshObject',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneMeshObject',
      classes: ['SceneObject', 'SceneMeshObject'],
      params: [],
    },
    {
      name: 'ScenePathArea',
      displayName: 'ScenePathArea',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathArea',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathAreaScatter',
      displayName: 'ScenePathAreaScatter',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathAreaScatter',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathArrangement',
      displayName: 'ScenePathArrangement',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathArrangement',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathArrangementTube',
      displayName: 'ScenePathArrangementTube',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathArrangementTube',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathCrossSection',
      displayName: 'ScenePathCrossSection',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathCrossSection',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathFlow',
      displayName: 'ScenePathFlow',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathFlow',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathLoft',
      displayName: 'ScenePathLoft',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathLoft',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathMeasureDevice',
      displayName: 'ScenePathMeasureDevice',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathMeasureDevice',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'ScenePathScatter',
      displayName: 'ScenePathScatter',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathScatter',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathTraffic',
      displayName: 'ScenePathTraffic',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathTraffic',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathVectorFieldArea',
      displayName: 'ScenePathVectorFieldArea',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathVectorFieldArea',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePathVolume',
      displayName: 'ScenePathVolume',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePathVolume',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'ScenePOI',
      displayName: 'ScenePOI',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePOI',
      classes: ['SceneObject', 'ScenePOI'],
      params: [],
    },
    {
      name: 'ScenePOI_Fx',
      displayName: 'ScenePOI_Fx',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePOI_Fx',
      classes: ['SceneObject', 'ScenePOI'],
      params: [],
    },
    {
      name: 'ScenePOI_Icon',
      displayName: 'ScenePOI_Icon',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePOI_Icon',
      classes: ['SceneObject', 'ScenePOI'],
      params: [],
    },
    {
      name: 'ScenePOI_Mesh',
      displayName: 'ScenePOI_Mesh',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePOI_Mesh',
      classes: ['SceneObject', 'ScenePOI'],
      params: [],
    },
    {
      name: 'ScenePointLight',
      displayName: 'ScenePointLight',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePointLight',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'ScenePowerNode',
      displayName: 'ScenePowerNode',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePowerNode',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'ScenePowerTower',
      displayName: 'ScenePowerTower',
      description: '',
      path: 'Class /Script/PiCIMOS.ScenePowerTower',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneProjectArea',
      displayName: 'SceneProjectArea',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneProjectArea',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneRoad',
      displayName: 'SceneRoad',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneRoad',
      classes: ['SceneObject', 'ScenePath'],
      params: [],
    },
    {
      name: 'SceneSelectionSet',
      displayName: 'SceneSelectionSet',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneSelectionSet',
      classes: ['SceneObject'],
      params: [],
    },
    {
      name: 'SceneSpotLight',
      displayName: 'SceneSpotLight',
      description: '',
      path: 'Class /Script/PiCIMOS.SceneSpotLight',
      classes: ['SceneObject'],
      params: [],
    },
  ],
  actions: [
    {
      name: 'test',
      displayName: '测试全类型参数',
      description: '',
      params: [
        {
          name: 'someClass',
          displayName: '类型',
          type: 'class',
          defaultValue: '',
          description: '',
        },
        {
          name: 'target',
          displayName: '目标对象',
          type: 'object',
          defaultValue: '',
          description: '',
        },
        {
          name: 'popPageId',
          displayName: 'POI页面',
          type: 'popPage',
          defaultValue: '',
          description: '',
        },
        {
          name: 'testStr',
          displayName: '字符串参数',
          type: 'string',
          defaultValue: '',
          description: '',
        },
        {
          name: 'testNum',
          displayName: '数值参数',
          type: 'number',
          step: 1,
          minValue: -360,
          maxValue: 360,
          defaultValue: '',
          description: '有最大值最小值限制',
        },
        {
          name: 'testNum1',
          displayName: '数值参数',
          type: 'number',
          step: 0.1,
          minValue: -100,
          maxValue: 100,
          hideInput: true,
          defaultValue: '',
          description: '有最大值最小值限制，隐藏输入框',
        },
        {
          name: 'testNum2',
          displayName: '数值参数',
          type: 'number',
          step: 0.001,
          defaultValue: '',
          description: '',
        },
        {
          name: 'testGeo',
          displayName: '地理坐标',
          type: 'geo',
          defaultValue: '',
          description: '',
        },
        {
          name: 'testVector',
          displayName: '场景坐标',
          type: 'vector',
          defaultValue: '',
          description: '',
        },
        {
          name: 'testRotation',
          displayName: '旋转',
          type: 'rotation',
          defaultValue: '',
          description: '',
        },
        {
          name: 'testBool',
          displayName: '某开关',
          type: 'boolean',
          defaultValue: '',
          description: 'boolean',
        },
        {
          name: 'testColor',
          displayName: '颜色',
          type: 'color',
          defaultValue: '',
          description: '',
        },
        {
          name: 'visible',
          displayName: '显隐',
          type: 'enum',
          options: [
            { name: '显示', value: 'show' },
            { name: '隐藏', value: 'hide' },
            { name: '切换显隐', value: 'toggle' },
          ],
          isRadio: true,
          defaultValue: '',
          description: '',
        },
        {
          name: 'weather',
          displayName: '天气',
          type: 'enum',
          options: [
            { name: '晴天', value: 'sunny' },
            { name: '多云', value: 'cloudy' },
            { name: '小雨', value: 'rain' },
            { name: '大雨', value: 'heavyRain' },
          ],
          defaultValue: '',
          description: '',
        },
      ],
    },
    {
      name: 'mode.enterEditMode',
      displayName: '模式-进入编辑模式',
      description: '进入编辑模式',
      params: [
        {
          name: 'modeId',
          type: 'number',
          displayName: '模式ID',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'mainPage',
          type: 'number',
          displayName: '主页面',
          description: '',
          defaultValue: '-1',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'subPage',
          type: 'number',
          displayName: '模式ID',
          description: '',
          defaultValue: '-1',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'mode.enterPlayMode',
      displayName: '模式-进入预览模式',
      description: '进入预览模式',
      params: [
        {
          name: 'defaultPageId',
          type: 'string',
          displayName: '默认页面ID',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'mode.event',
      displayName: '模式-通用事件',
      description: '通用的事件触发，从外部通知PiClient事件的发生',
      params: [
        {
          name: 'action',
          type: 'string',
          displayName: '动作',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'target',
          type: 'object',
          displayName: '目标',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'params',
          type: 'string',
          displayName: '项目名',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'object.create',
      displayName: '对象-创建',
      description: '创建对象',
      params: [
        {
          name: 'className',
          type: 'string',
          displayName: '类型名称',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'classPath',
          type: 'string',
          displayName: '类型路径',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'ecef',
          type: 'string',
          displayName: 'ecef坐标',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'geo',
          type: 'string',
          displayName: '经纬度坐标',
          description: '经度,纬度,高程 高程为可选值',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'rotation',
          type: 'string',
          displayName: '朝向',
          description: 'roll,pitch,yaw',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'object.move',
      displayName: '对象-移动',
      description:
        '移动对象，参数offset/ecef/geo三选一，都提供则geo >> ecef >> offset',
      params: [
        {
          name: 'target',
          type: 'object',
          displayName: '目标',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'parent',
          type: 'object',
          displayName: '父对象',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'offset',
          type: 'string',
          displayName: '偏移量',
          description: 'x,y,z',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'ecef',
          type: 'vector',
          displayName: '地心坐标',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'geo',
          type: 'geo',
          displayName: '经纬度',
          description: '经度,纬度,高程',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'rotation',
          type: 'rotation',
          displayName: '朝向',
          description: 'roll,pitch,yaw',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'object.visible',
      displayName: '对象-显示隐藏',
      description: '显示隐藏对象',
      params: [
        {
          name: 'target',
          type: 'object',
          displayName: '目标',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'visible',
          type: 'enum',
          displayName: '显隐',
          description: '',
          defaultValue: 'toggle',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: true,
          options: [
            { name: '显示', value: 'show' },
            { name: '隐藏', value: 'hide' },
            { name: '切换', value: 'toggle' },
          ],
        },
      ],
    },
    {
      name: 'object.destroy',
      displayName: '对象-销毁',
      description: '销毁对象',
      params: [
        {
          name: 'target',
          type: 'object',
          displayName: '目标',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'object.setmpc',
      displayName: 'object.setmpc',
      description: '设置材质参数集',
      params: [
        {
          name: 'MPCName',
          type: 'string',
          displayName: '参数集名',
          description: '材质参数集名称 material parameter collections',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'ParamName',
          type: 'string',
          displayName: '参数名',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'ParamValue',
          type: 'string',
          displayName: '参数值',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'object.layerVisible',
      displayName: '对象-图层显隐',
      description: '图层显隐',
      params: [
        {
          name: 'layerName',
          type: 'string',
          displayName: '图层名',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'visible',
          type: 'enum',
          displayName: '可见性',
          description: '',
          defaultValue: 'toggle',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: true,
          options: [
            { name: '显示', value: 'show' },
            { name: '隐藏', value: 'hide' },
            { name: '切换', value: 'toggle' },
          ],
        },
      ],
    },
    {
      name: 'camera.focus',
      displayName: '聚焦相机到对象',
      description: '聚焦相机到对象',
      params: [
        {
          name: 'target',
          type: 'object',
          displayName: '目标',
          description: '场景中的任意对象',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'camera.fly',
      displayName: '相机飞行',
      description: '相机飞行',
      params: [
        {
          name: 'target',
          type: 'object',
          displayName: '目标',
          description: '场景中的任意对象',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'ecef',
          type: 'vector',
          displayName: 'ECEF',
          description: 'ECEF地心坐标',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'rotation',
          type: 'rotation',
          displayName: '朝向',
          description: '旋转 roll, pitch, yaw的角度值',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'geo',
          type: 'geo',
          displayName: '经纬度',
          description: '经度,纬度,高程 组成的格式，高程可选',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'time',
          type: 'number',
          displayName: '时长',
          description: '飞行时长，单位秒',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'camera.animControl',
      displayName: '相机动画控制',
      description: '相机动画控制，设置动画时长，播放，暂停，停止',
      params: [
        {
          name: 'target',
          type: 'object',
          displayName: '目标',
          description: '场景中的任意对象',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'totalTime',
          type: 'number',
          displayName: '总时长',
          description: '动画的播放时长',
          defaultValue: '3.5',
          minValue: 0,
          maxValue: 1000,
          step: 1,
          isRadio: false,
        },
        {
          name: 'bFromStart',
          type: 'boolean',
          displayName: '从头开始',
          description: '是否从头开始播放',
          defaultValue: 'true',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'playState',
          type: 'enum',
          displayName: '状态',
          description: '动画的播放状态',
          defaultValue: 'toggle',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: true,
          options: [
            { name: '停止', value: 'stop' },
            { name: '暂停', value: 'pause' },
            { name: '播放', value: 'play' },
            { name: '切换', value: 'toggle' },
          ],
        },
      ],
    },
    {
      name: 'environment.setTime',
      displayName: '环境-设置时间',
      description: '设置时间',
      params: [
        {
          name: 'hour',
          type: 'number',
          displayName: '小时',
          description: '',
          defaultValue: '13',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'minute',
          type: 'number',
          displayName: '分钟',
          description: '',
          defaultValue: '32',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'percentOfDay',
          type: 'number',
          displayName: '百分比',
          description: '一天的百分比，大于0时hour/minute无效',
          defaultValue: '0',
          minValue: 0,
          maxValue: 1,
          step: 0.10000000149011612,
          isRadio: false,
        },
      ],
    },
    {
      name: 'environment.setWeather',
      displayName: '环境-设置天气',
      description: '设置天气',
      params: [
        {
          name: 'weather',
          type: 'enum',
          displayName: '天气',
          description: '',
          defaultValue: '2',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
          options: [
            { name: '晴空万里', value: '0' },
            { name: '少云', value: '1' },
            { name: '多云', value: '2' },
            { name: '阴天', value: '3' },
            { name: '雾天', value: '4' },
            { name: '小雨', value: '5' },
            { name: '中雨', value: '6' },
            { name: '暴风雨', value: '7' },
            { name: '小雪', value: '8' },
            { name: '中雪', value: '9' },
            { name: '暴风雪', value: '10' },
          ],
        },
      ],
    },
    {
      name: 'environment.timepass',
      displayName: 'environment.timepass',
      description: '时光流逝控制',
      params: [],
    },
    {
      name: 'general.openUrl',
      displayName: '通用-打开网页地址',
      description: '打开URL',
      params: [
        {
          name: 'url',
          type: 'string',
          displayName: '地址',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.getDb',
      displayName: '电力-获取基础数据',
      description: '获取基础数据',
      params: [],
    },
    {
      name: 'power.query',
      displayName: '电力-查询节点数据',
      description: '查询节点数据',
      params: [
        {
          name: 'search',
          type: 'string',
          displayName: '搜索关键字',
          description: '搜索关键字，空表示不参与搜索',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'network',
          type: 'string',
          displayName: '网络id',
          description: 'network.id，空表示不参与搜索',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'modal',
          type: 'string',
          displayName: '模型id',
          description: 'nodeModal.id，空表示不参与搜索',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'voltageMin',
          type: 'number',
          displayName: '最低电压',
          description: '最低电压，0或空表示不参与搜索',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'voltageMax',
          type: 'number',
          displayName: '最高电压',
          description: '最高电压， 0或空表示不参与搜索',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'isCreated',
          type: 'boolean',
          displayName: '是否创建',
          description: '是否创建，空表示不参与搜索',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'page',
          type: 'number',
          displayName: '页码',
          description: '第几页结果，从1开始，空或<1 则默认1',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'pageSize',
          type: 'number',
          displayName: '每页数量',
          description: '结果数量，空或<1，则默认10000',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.create',
      displayName: '电力-创建节点',
      description: '创建节点',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.remove',
      displayName: '电力-删除节点',
      description: '删除节点',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.connect',
      displayName: '电力-查询节点数据',
      description: '查询节点数据',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.disconnect',
      displayName: '电力-断开节点',
      description: '断开节点',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.focus',
      displayName: '电力-聚焦节点',
      description: '聚焦节点',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.nodeShow',
      displayName: '电力-模型特写',
      description: '电力模型特写',
      params: [
        {
          name: 'nodeid',
          type: 'string',
          displayName: '节点ID',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'enter',
          type: 'boolean',
          displayName: '',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.boom',
      displayName: '电力-节点展开',
      description: '电力节点展开',
      params: [
        {
          name: 'nodeid',
          type: 'string',
          displayName: '节点ID',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'expand',
          type: 'boolean',
          displayName: '是否展开',
          description: '是否展开模型零件，爆炸图效果',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.publish',
      displayName: '电力-发布节点',
      description: '电力节点发布',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.reset',
      displayName: '电力-重置节点改动',
      description: '重置电力节点改动',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.save',
      displayName: '电力-保存节点改动',
      description: '保存电力节点改动',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.detail',
      displayName: '电力-节点详情数据',
      description: '查询节点详情数据',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'power.nodeEdit',
      displayName: '电力-编辑节点',
      description: '编辑节点',
      params: [
        {
          name: 'nodes',
          type: 'string',
          displayName: '节点列表',
          description: '["",""] //node id 列表',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'begin',
          type: 'boolean',
          displayName: '是否开始',
          description: '',
          defaultValue: 'false',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'project.new',
      displayName: '项目-新建项目',
      description: '新建项目',
      params: [
        {
          name: 'projectName',
          type: 'string',
          displayName: '项目名',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'geoPos',
          type: 'geo',
          displayName: '地理位置',
          description: '项目地理位置',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'radius',
          type: 'number',
          displayName: '区域半径',
          description: '项目区域的半径，单位米',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'project.load',
      displayName: '项目-加载项目',
      description: '加载项目',
      params: [
        {
          name: 'projectId',
          type: 'string',
          displayName: '项目ID',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'showUI',
          type: 'boolean',
          displayName: '编辑器UI',
          description: '是否显示编辑器UI',
          defaultValue: 'false',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'editorMode',
          type: 'boolean',
          displayName: '进入编辑模式',
          description: '是否进入编辑模式',
          defaultValue: 'false',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
    {
      name: 'project.save',
      displayName: '项目-保存项目',
      description: '保存项目',
      params: [],
    },
    {
      name: 'cloud.init',
      displayName: '云渲染-云渲染初始化',
      description: '云渲染初始化',
      params: [
        {
          name: 'accountId',
          type: 'string',
          displayName: '账号ID',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'accountName',
          type: 'string',
          displayName: '账号名',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'token',
          type: 'string',
          displayName: 'token',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'projectId',
          type: 'string',
          displayName: '项目ID',
          description: '',
          defaultValue: '',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'showUI',
          type: 'boolean',
          displayName: '编辑器UI',
          description: '是否显示编辑器UI',
          defaultValue: 'false',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
        {
          name: 'editorMode',
          type: 'boolean',
          displayName: '进入编辑模式',
          description: '是否进入编辑模式',
          defaultValue: 'false',
          minValue: 0,
          maxValue: 0,
          step: 0,
          isRadio: false,
        },
      ],
    },
  ],
  classEvents: {
    SceneObject: [
      { name: 'objectClick', displayName: '点击', description: '' },
      {
        name: 'move',
        displayName: '移动',
        description: '',
        params: [
          {
            name: 'position',
            displayName: '位置',
            type: 'vector',
            defaultValue: '',
            description: '',
          },
          {
            name: 'rotation',
            displayName: '朝向',
            type: 'vector',
            defaultValue: '',
            description: '',
          },
          {
            name: 'offset',
            displayName: '偏移',
            type: 'vector',
            defaultValue: '',
            description: '',
          },
        ],
      },
      {
        name: 'scale',
        displayName: '缩放',
        description: '',
        params: [
          {
            name: 'scale',
            displayName: '缩放',
            type: 'vector',
            defaultValue: '',
            description: '',
          },
        ],
      },
      {
        name: 'visible',
        displayName: '显隐',
        description: '',
        params: [
          {
            name: 'visible',
            displayName: '显隐',
            type: 'string',
            defaultValue: '',
            description: 'show=显示,hide=隐藏,toggle=切换',
          },
        ],
      },
      { name: 'objectCreated', displayName: '创建', description: '' },
      { name: 'objectDestroyed', displayName: '销毁', description: '' },
      {
        name: 'attach',
        displayName: '附加',
        description: '',
        params: [
          {
            name: 'parent',
            displayName: '父对象',
            type: 'string',
            defaultValue: '',
            description: '',
          },
        ],
      },
      {
        name: 'detach',
        displayName: '脱离',
        description: '',
        params: [
          {
            name: 'parent',
            displayName: '父对象',
            type: 'string',
            defaultValue: '',
            description: '',
          },
        ],
      },
    ],
    SceneMeshObject: [
      {
        name: 'meshChange',
        displayName: '模型变更',
        description: '',
        params: [
          {
            name: 'meshId',
            displayName: '模型ID',
            type: 'string',
            defaultValue: '',
            description: '',
          },
          {
            name: 'meshPath',
            displayName: '模型路径',
            type: 'string',
            defaultValue: '',
            description: '',
          },
          {
            name: 'compIndex',
            displayName: '组件序号',
            type: 'number',
            defaultValue: '',
            description: '',
          },
        ],
      },
      {
        name: 'materialChange',
        displayName: '材质变更',
        description: '',
        params: [
          {
            name: 'compIndex',
            displayName: '组件序号',
            type: 'number',
            defaultValue: '',
            description: '',
          },
          {
            name: 'sectIndex',
            displayName: '块序号',
            type: 'number',
            defaultValue: '',
            description: '',
          },
          {
            name: 'matId',
            displayName: '材质ID',
            type: 'string',
            defaultValue: '',
            description: '',
          },
          {
            name: 'matPath',
            displayName: '材质路径',
            type: 'string',
            defaultValue: '',
            description: '',
          },
        ],
      },
    ],
    ScenePath: [],
    ScenePOI: [
      { name: 'iconChange', displayName: '图表变更', description: '' },
      { name: 'titleChange', displayName: '文字变更', description: '' },
      { name: 'stateChange', displayName: '状态变更', description: '' },
      { name: 'iconVisible', displayName: '图表显隐', description: '' },
      { name: 'menuVisible', displayName: '菜单开闭', description: '' },
    ],
    SceneIOT: [
      {
        name: 'valueChange',
        displayName: '数值变更',
        description: '比如压力的大小变化，但不一定触发状态变化',
        params: [
          {
            name: 'value',
            displayName: '新值',
            type: 'string',
            defaultValue: '',
            description: '',
          },
          {
            name: 'valueOld',
            displayName: '旧值',
            type: 'string',
            defaultValue: '',
            description: '',
          },
        ],
      },
      {
        name: 'stateChange',
        displayName: '状态变更',
        description: '比如从正常状态变为警告状态或者离线状态',
        params: [
          {
            name: 'state',
            displayName: '新状态',
            type: 'string',
            defaultValue: '',
            description: '',
          },
          {
            name: 'stateOld',
            displayName: '旧状态',
            type: 'string',
            defaultValue: '',
            description: '',
          },
        ],
      },
    ],
  },
  globalObjects: [
    { name: 'world', displayName: '3D世界', description: '代表整个三维空间' },
    {
      name: 'camera',
      displayName: '相机',
      description: '代表当前视野的提供者',
    },
    {
      name: 'env',
      displayName: '环境',
      description: '环境，包括光照，后处理，音效等',
    },
  ],
  worldObjects: [
    {
      name: 'SceneCamera_0',
      displayName: 'SceneCamera_0',
      class: 'SceneCamera',
    },
    {
      name: 'SceneCamera_2',
      displayName: 'SceneCamera_2',
      class: 'SceneCamera',
    },
    {
      name: 'SceneCamera_3',
      displayName: 'SceneCamera_3',
      class: 'SceneCamera',
    },
    {
      name: 'SceneCamera_4',
      displayName: 'SceneCamera_4',
      class: 'SceneCamera',
    },
    {
      name: 'SceneCamera_5',
      displayName: 'SceneCamera_5',
      class: 'SceneCamera',
    },
    {
      name: 'SceneCompass_1',
      displayName: 'SceneCompass_1',
      class: 'SceneCompass',
    },
    {
      name: 'SceneMeshObject_0',
      displayName: 'JM_493_1',
      class: 'SceneMeshObject',
    },
    {
      name: 'SceneMeshObject_1',
      displayName: 'JM_494_1',
      class: 'SceneMeshObject',
    },
    {
      name: 'SceneMeshObject_2',
      displayName: 'JM_497_1',
      class: 'SceneMeshObject',
    },
    {
      name: 'SceneMeshObject_3',
      displayName: 'JM_493_2',
      class: 'SceneMeshObject',
    },
    {
      name: 'SceneMeshObject_4',
      displayName: 'JM_497_2',
      class: 'SceneMeshObject',
    },
  ],
}
